project_name: python-docs-rag
seed_domain: docs.python.org # stay in-domain for crawl
seeds_file: data/seeds.txt


scrape:
  max_pages: 150
  same_domain_only: true
  timeout_sec: 15


chunk:
  target_tokens: 800
  overlap_tokens: 120


embeddings:
  model_name: intfloat/e5-small-v2
  batch_size: 64


index:
  faiss_path: index/faiss.index
  meta_path: index/meta.jsonl


retriever:
  top_k: 5
  use_mmr: true
  mmr_lambda: 0.5
  min_score: 0.25 # below this -> “I don’t know”


llm:
  provider: ollama # one of: ollama | openai
  model: mistral:instruct #gpt-5 # or llama3.1:8b-instruct
  temperature: 0.2
  max_tokens: 512
  timeout_sec: 60


ui:
  title: "Python Help Bot (RAG)"
  banned_queries: ["medical", "diagnosis", "financial advice"]